AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
  Excludes:
    - recipes/**
    - spec/**

# ignore long lines
LineLength:
  Enabled: false

# Allow small arrays before forcing  %w or %W
WordArray:
  MinSize: 3
